per_variable_kwargs:
  # See visualize.py for total_precipitation_6hr
  10m_wind_speed:
    cmap: cmo.tempo_r
    vmin: 0
    vmax: 20
  2m_specific_humidity:
    cmap: cmo.rain
    vmin: 0
    vmax: 0.025
  2m_temperature:
    cmap: cmo.thermal
    vmin: -10
    vmax: 30
  80m_wind_speed:
    cmap: cmo.tempo_r
    vmin: 0
    vmax: 20
  specific_humidity:
    cmap: cmo.rain
    vmin: 0
    vmax: 0.025
  temperature:
    cmap: cmo.thermal
    vmin: -10
    vmax: 30
  wind_speed:
    cmap: cmo.tempo_r
    vmin: 0
    vmax: 20

fig_kwargs:
  dpi: 300
  width: 10
  height: 4.5
  projection: Robinson
  lam_size: 0.25
  global_size: 12

  # Orthographic Projection example
  # height: 7
  # projection: Orthographic
  # projection_kwargs:
  #   central_longitude: -120
  #   central_latitude: 20

units:
  10m_wind_speed: m/s
  80m_wind_speed: m/s
  100m_wind_speed: m/s
  wind_speed: m/s
  10m_zonal_wind: m/s
  80m_zonal_wind: m/s
  100m_zonal_wind: m/s
  zonal_wind: m/s
  10m_meridional_wind: m/s
  80m_meridional_wind: m/s
  100m_meridional_wind: m/s
  meridional_wind: m/s
  2m_specific_humidity: kg/kg
  specific_humidity: kg/kg
  2m_temperature: K
  temperature: K
  total_precipitation_6hr: mm
